#!/bin/zsh
VERSION_LIST_CURR=$(cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2)
CMD_DB_UPDATE=$(sudo pacman -Sy | grep -o silent)

# Update pacman DB before starting any update.
${CMD_DB_UPDATE}
sleep 1
# Define update variables only after DB update, to make sure queries are going to be made properly.
CMD_HOLOISO_CHECK_FOR_UPDATES=$(pacman -Qu | grep -e holoiso-main -e holoiso-updateclient -e nvidia -e mesa -e vulkan -e linux)
CMD_HOLOISO_CHECK_FOR_NVGPU_UPDATES=$(pacman -Qu | grep -e nvidia)
CMD_HOLOISO_CHECK_FOR_KERNEL_UPDATES=$(pacman -Qu | grep -e linux)
IS_NVIDIA=$(echo $(lspci | grep VGA | cut -d ':' -f 3) | grep NVIDIA)
CMD_CHECK_BETA_BRANCH=$(cat /etc/holoiso-branch)

# Check for available OS updates. Make sure to only check for snapshot updates
updatecheck() {
    if [ -n "${CMD_HOLOISO_CHECK_FOR_UPDATES}" ]; then
        echo "Update(s) available:"
        echo "${CMD_HOLOISO_CHECK_FOR_UPDATES}"
        touch /tmp/steamos-updatepersist-sentinel
        exit 0
    else
        echo "System up to date."
        exit 7
    fi
}

# Check for kernel updates. Little workaround to make it work on HoloISO
checkkernelupd() {
    if [ -n "${CMD_HOLOISO_CHECK_FOR_KERNEL_UPDATES}" ]; then
        echo "Kernel update available, updating..."
        sudo pacman -Rcns linux linux-headers
        sudo pacman -S --noconfirm --needed linux-holoiso linux-holoiso-headers linux-neptune-dri linux-neptune-dri-headers
        sudo depmod -a $(ls /lib/modules)
        sudo mkinitcpio -P
        sudo grub-mkconfig -o /boot/grub/grub.cfg
    else
        echo "Kernel update not required, skipping."
    fi
}

# We do not want to overwrite GPU drivers by old Syyu command, update GPU drivers as if it would be a regular package installation
checkgpuupd() {
if [ -n "${IS_NVIDIA}" ]; then
    if [ -n "${CMD_HOLOISO_CHECK_FOR_NVGPU_UPDATES}" ]; then
        echo "NVIDIA GPU Driver update available, updating..."
        sudo pacman -S --noconfirm --needed nvidia-dkms opencl-nvidia nvidia-utils lib32-nvidia-utils
        sudo depmod -a $(ls /lib/modules)
        sudo mkinitcpio -P
        sudo grub-mkconfig -o /boot/grub/grub.cfg
    else
        echo "NVIDIA GPU Driver update not required, skipping."
    fi
else
    echo "No NVIDIA GPU, skipping update."
fi
}

# Check for sentinel. Sentinel detected = Update time!
export STEAMOS_UPDATE_SENTINEL="/tmp/steamos-updatepersist-sentinel"
if [[ -e "$STEAMOS_UPDATE_SENTINEL" ]]; then
  rm -f "$STEAMOS_UPDATE_SENTINEL"
    sudo pacman -Sy --noconfirm --needed holoiso-main;
    checkkernelupd
    checkgpuupd
    echo "HoloISO Update complete, checking OS updates..."
    sudo pacman -Syyu --noconfirm --needed --ignore=grub --ignore=linux
    sudo depmod -a $(ls /lib/modules)
    sudo mkinitcpio -P
    sudo grub-mkconfig -o /boot/grub/grub.cfg
    echo "Update complete. Restart your device to finish."
fi


# if [[ "${DESKTOP_SESSION}" == "plasma" ]]; then
#        echo "HoloISO Updater Beta 1\nCurrent version: ${VERSION_LIST_PRE}\nChecking for updates..."
#fi
#CMD_HOLO_UPDATE=$(sudo pacman -Syyu --noconfirm --needed --ignore=linux-firmware --ignore=grub --ignore=linux --overwrite="*" --quiet | grep nothing)
#VERSION_LIST=$(cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2)
#if [[ "${CMD_HOLO_UPDATE}" == " there is nothing to do" ]]; then
#    echo "Your system is up to date."
#    echo "Current version: ${VERSION_LIST_PRE}"
#    exit 7
#else
#    echo "Update complete to version ${VERSION_LIST}. Please restart your device to apply changes."
#fi

if [ -n "$1" ]; then
    case "$1" in
    check)
        updatecheck
        ;;
    '')
        updatenow
        ;;
    esac
    shift
fi
